version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    #hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:1:3,test:1:1:compact,wordcount-input:1:2,wordcount-output:1:2"
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      #elsei
      #
      #GET_HOSTNAME_COMMAND: "echo `hostname`"
      PORT_COMMAND: "docker port `hostname` 9092/tcp | cut -d: -f2 || echo '-1'"
      #KAFKA_ADVERTISED_HOST_NAME: "${DOCKERHOSTMACHINEIP}"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:29092,OUTSIDE://${DOCKERHOSTMACHINEIP}:_{PORT_COMMAND}
      #alt KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://${DOCKERHOSTMACHINEIP}:_{PORT_COMMAND}
      #KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:_{PORT_COMMAND}
      #KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
